# MeshCore.podspec
#
# Consumed by the app's Podfile via `pod 'MeshCore', :path => '../mesh/ios'`
# (or automatically, if this package is published as an npm package with this
# podspec at its root — RN autolinking finds `*.podspec`).
#
# What ships:
#   * MeshCore.xcframework  — the Rust static library, built by
#     scripts/build-ios.sh into device + simulator slices.
#   * shared/cpp/*          — the JSI HostObject, identical to Android's copy.
#   * ios/MeshCore/*        — CoreBluetooth radio + Turbo Module shim.
#
# The Rust archive is a *static* library on purpose. A dynamic framework would
# add a dlopen at launch and force us to code-sign a second binary; a static
# archive gets LTO'd into the app binary and disappears from the launch path.

require "json"

package = JSON.parse(File.read(File.join(__dir__, "..", "js", "package.json")))

Pod::Spec.new do |s|
  s.name         = "MeshCore"
  s.version      = package["version"]
  s.summary      = "Rust mesh messaging core for React Native"
  s.license      = package["license"]
  s.authors      = package["author"]
  s.homepage     = package["homepage"] || "https://example.invalid/meshcore"
  s.platforms    = { :ios => "13.0" }
  s.source       = { :path => "." }

  s.source_files = [
    "MeshCore/**/*.{h,m,mm}",
    "../shared/cpp/**/*.{h,cpp}",
  ]

  # The Rust slices. Built by scripts/build-ios.sh; not in git.
  s.vendored_frameworks = "Frameworks/MeshCore.xcframework"

  s.pod_target_xcconfig = {
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
    # `meshcore.h` is generated by cbindgen into the Rust crate; the build
    # script copies it next to the xcframework so this path is stable.
    "HEADER_SEARCH_PATHS" => [
      '"$(PODS_TARGET_SRCROOT)/../shared/cpp"',
      '"$(PODS_TARGET_SRCROOT)/Frameworks/include"',
    ].join(" "),
    "OTHER_CPLUSPLUSFLAGS" => "-fno-omit-frame-pointer",
    "DEFINES_MODULE" => "YES",
  }

  # BLE on iOS needs these in the app's Info.plist. Listed here so the failure
  # mode is a review rejection at build time rather than a silent no-op radio:
  #   NSBluetoothAlwaysUsageDescription
  #   UIBackgroundModes = [bluetooth-central, bluetooth-peripheral]

  s.dependency "React-Core"
  s.dependency "React-callinvoker"
  s.dependency "React-jsi"

  # New Architecture wiring (codegen, Fabric, TurboModules). No-op on old arch.
  if respond_to?(:install_modules_dependencies, true)
    install_modules_dependencies(s)
  end
end
