//! # meshcore-ffi
//!
//! The only crate in the workspace containing `#[no_mangle]`, `extern "C"` or
//! JNI. Everything here is a thin, panic-safe, null-safe adapter over
//! [`meshcore`] — no protocol logic lives at this layer, so a bug is either a
//! marshalling bug (caught by the tests in this crate) or a core bug (caught by
//! `meshcore`'s host tests).
//!
//! Artifacts:
//!
//! * `libmeshcore_ffi.a`  — iOS/tvOS/simulator, linked into an XCFramework.
//! * `libmeshcore_ffi.so` — Android, packed into `jniLibs/<abi>/`.
//! * `meshcore.h`         — generated by `cbindgen` at build time (see build.rs).

#![deny(improper_ctypes_definitions)]

pub mod android;
pub mod buffer;
pub mod c_api;

pub use buffer::{mesh_buffer_free, MeshBuffer};
pub use c_api::{
    mesh_abi_version, mesh_core_free, mesh_core_new, mesh_core_public_key,
    mesh_core_set_event_sink, mesh_ingest, mesh_is_running, mesh_last_error, mesh_peers,
    mesh_receive_message, mesh_send_message, mesh_start_broadcasting, mesh_stop_broadcasting,
    MeshConfig, MeshEventSink, MeshHandle, MeshPlatformRadio, MeshStatus,
};
